/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Physical AI & Humanoid Robotics",
  "tagline": "From ROS 2 to Vision-Language-Action Systems",
  "favicon": "img/favicon.ico",
  "url": "https://salwagull.github.io",
  "baseUrl": "/Physical-AI-And-Humanoid-Robotics/",
  "organizationName": "Salwagull",
  "projectName": "Physical-AI-And-Humanoid-Robotics",
  "trailingSlash": false,
  "deploymentBranch": "gh-pages",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "routeBasePath": "/",
          "editUrl": "https://github.com/Salwagull/Physical-AI-And-Humanoid-Robotics/tree/main/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/logo.svg",
    "navbar": {
      "title": "Physical AI & Robotics",
      "logo": {
        "alt": "Physical AI Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "to": "/intro",
          "label": "Introduction",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "Chapters",
          "position": "left",
          "items": [
            {
              "type": "html",
              "value": "<span class=\"dropdown-header\">Module 1: Foundations</span>"
            },
            {
              "to": "/chapters/physical-ai-foundations",
              "label": "1. Physical AI Foundations"
            },
            {
              "to": "/chapters/ros2-essentials",
              "label": "2. ROS 2 Essentials"
            },
            {
              "to": "/chapters/gazebo-simulation",
              "label": "3. Gazebo Simulation"
            },
            {
              "type": "html",
              "value": "<span class=\"dropdown-header\">Module 2: Digital Twins</span>"
            },
            {
              "to": "/chapters/unity-digital-twins",
              "label": "4. Unity Digital Twins"
            },
            {
              "type": "html",
              "value": "<span class=\"dropdown-header\">Module 3: AI-Native</span>"
            },
            {
              "to": "/chapters/isaac-sim-setup",
              "label": "5. Isaac Sim Setup"
            },
            {
              "to": "/chapters/perception-vision",
              "label": "6. Perception & Vision"
            },
            {
              "to": "/chapters/control-planning",
              "label": "7. Control & Planning"
            },
            {
              "type": "html",
              "value": "<span class=\"dropdown-header\">Module 4: VLA</span>"
            },
            {
              "to": "/chapters/vla-systems-intro",
              "label": "8. VLA Systems Intro"
            },
            {
              "to": "/chapters/voice-robotics",
              "label": "9. Voice-Driven Robotics"
            },
            {
              "type": "html",
              "value": "<span class=\"dropdown-header\">Module 5: Capstone</span>"
            },
            {
              "to": "/chapters/capstone-architecture",
              "label": "10. Capstone Architecture"
            },
            {
              "to": "/chapters/capstone-implementation",
              "label": "11. Capstone Implementation"
            },
            {
              "to": "/chapters/testing-validation",
              "label": "12. Testing & Validation"
            },
            {
              "to": "/chapters/deployment-next-steps",
              "label": "13. Deployment & Next Steps"
            }
          ]
        },
        {
          "to": "/glossary",
          "label": "Glossary",
          "position": "left"
        },
        {
          "href": "https://github.com/Salwagull/Physical-AI-And-Humanoid-Robotics",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Learn",
          "items": [
            {
              "label": "Introduction",
              "to": "/intro"
            },
            {
              "label": "Chapter 1: Physical AI",
              "to": "/chapters/physical-ai-foundations"
            },
            {
              "label": "Glossary",
              "to": "/glossary"
            }
          ]
        },
        {
          "title": "Modules",
          "items": [
            {
              "label": "Foundations & Communication",
              "to": "/chapters/ros2-essentials"
            },
            {
              "label": "AI-Native Robotics",
              "to": "/chapters/isaac-sim-setup"
            },
            {
              "label": "Vision-Language-Action",
              "to": "/chapters/vla-systems-intro"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/Salwagull/Physical-AI-And-Humanoid-Robotics"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Physical AI & Humanoid Robotics. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "backgroundColor": "hsl(220, 13%, 18%)",
          "color": "hsl(220, 14%, 71%)",
          "textShadow": "0 1px rgba(0, 0, 0, 0.3)"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "cdata"
            ],
            "style": {
              "color": "hsl(220, 10%, 40%)"
            }
          },
          {
            "types": [
              "doctype",
              "punctuation",
              "entity"
            ],
            "style": {
              "color": "hsl(220, 14%, 71%)"
            }
          },
          {
            "types": [
              "attr-name",
              "class-name",
              "maybe-class-name",
              "boolean",
              "constant",
              "number",
              "atrule"
            ],
            "style": {
              "color": "hsl(29, 54%, 61%)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "hsl(286, 60%, 67%)"
            }
          },
          {
            "types": [
              "property",
              "tag",
              "symbol",
              "deleted",
              "important"
            ],
            "style": {
              "color": "hsl(355, 65%, 65%)"
            }
          },
          {
            "types": [
              "selector",
              "string",
              "char",
              "builtin",
              "inserted",
              "regex",
              "attr-value"
            ],
            "style": {
              "color": "hsl(95, 38%, 62%)"
            }
          },
          {
            "types": [
              "variable",
              "operator",
              "function"
            ],
            "style": {
              "color": "hsl(207, 82%, 66%)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "hsl(187, 47%, 55%)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "textDecorationLine": "line-through"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "textDecorationLine": "underline"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "color": "hsl(220, 14%, 71%)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "backgroundColor": "hsl(220, 13%, 18%)",
          "color": "hsl(220, 14%, 71%)",
          "textShadow": "0 1px rgba(0, 0, 0, 0.3)"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "cdata"
            ],
            "style": {
              "color": "hsl(220, 10%, 40%)"
            }
          },
          {
            "types": [
              "doctype",
              "punctuation",
              "entity"
            ],
            "style": {
              "color": "hsl(220, 14%, 71%)"
            }
          },
          {
            "types": [
              "attr-name",
              "class-name",
              "maybe-class-name",
              "boolean",
              "constant",
              "number",
              "atrule"
            ],
            "style": {
              "color": "hsl(29, 54%, 61%)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "hsl(286, 60%, 67%)"
            }
          },
          {
            "types": [
              "property",
              "tag",
              "symbol",
              "deleted",
              "important"
            ],
            "style": {
              "color": "hsl(355, 65%, 65%)"
            }
          },
          {
            "types": [
              "selector",
              "string",
              "char",
              "builtin",
              "inserted",
              "regex",
              "attr-value"
            ],
            "style": {
              "color": "hsl(95, 38%, 62%)"
            }
          },
          {
            "types": [
              "variable",
              "operator",
              "function"
            ],
            "style": {
              "color": "hsl(207, 82%, 66%)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "hsl(187, 47%, 55%)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "textDecorationLine": "line-through"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "textDecorationLine": "underline"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "color": "hsl(220, 14%, 71%)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "yaml",
        "python"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
